import Mailchimp, { MessagesMessage } from "@mailchimp/mailchimp_transactional";
import { NextResponse } from "next/server";

const MAILCHIMP_TRANSACTIONAL_API_KEY =
  process.env.MAILCHIMP_TRANSACTIONAL_API_KEY;
if (!MAILCHIMP_TRANSACTIONAL_API_KEY)
  throw new Error("[MAILCHIMP_TRANSACTIONAL_API_KEY] is required");

const mailchimp = Mailchimp(MAILCHIMP_TRANSACTIONAL_API_KEY);

export async function POST(req: Request) {
  const reqData: {
    firstname: string;
    lastname: string;
    email: string;
    reason?: string;
    message?: string;
    locale: string;
    requested_at: string;
  } = await req.json();
  const { firstname, lastname, email, reason, message, locale, requested_at } =
    reqData;

  if (!email) {
    console.log(`No email provided.`);
    return NextResponse.json({ error: "invalid email" }, { status: 400 });
  }

  // TODO: in case we want to send any email to domain outside of scintillar.com
  // we have to upgrade plan https://us22.admin.mailchimp.com/account/blocks/
  const msg: MessagesMessage = {
    from_email: "noreply@scintillar.com",
    from_name: "noreply",
    subject: "scintillar.com | Contact Request",
    html: `
      <p>Hello,</p>
      <p>This email was generated by <strong>scintillar.com</strong>. A contact request has been received.</p>
      <p>Here is the information provided by the user:</p>
      <table border="1" cellpadding="5" cellspacing="0">
        <tr>
          <th>Firstname</th>
          <td>${firstname}</td>
        </tr>
        <tr>
          <th>Lastname</th>
          <td>${lastname}</td>
        </tr>
        <tr>
          <th>Email</th>
          <td>${email}</td>
        </tr>
        <tr>
          <th>Reason</th>
          <td>${reason}</td>
        </tr>
        <tr>
          <th>Message</th>
          <td>${message}</td>
        </tr>
        <tr>
          <th>Language</th>
          <td>${locale}</td>
        </tr>
        <tr>
          <th>Request Time</th>
          <td>${requested_at}</td>
        </tr>
      </table>
      <p>Please follow up ASAP.</p>
      <p>Thanks.</p>
    `,
    to: [
      {
        email: "dominic@scintillar.com",
        name: "Dominic Fournier",
        type: "to",
      },
    ],
  };

  try {
    const response: any = await mailchimp.messages.send({
      message: msg,
    });
    if (response[0]?.status !== "sent") {
      const msg = { code: 400, message: response };
      console.log(
        `Unable to send the contact form submission email to Scintillar's Team for user ${email}.`,
        response
      );
      return NextResponse.json(msg, { status: 400 });
    }
    console.log(
      `Contact form submission email sent to Scintillar's Team for user ${email}.`
    );
    return NextResponse.json(
      {
        status: "ok",
        message: "Contact Submission Email Sent to Scintillar's Team.",
      },
      { status: 200 }
    );
  } catch (e: any) {
    const msg = { code: 400, message: e };
    console.log(
      `Unable to send the contact form submission email to Scintillar's Team for user ${email}.`
    );
    return NextResponse.json(msg, { status: 400 });
  }
}
