// This file is generated by docs-index.script.ts. Do not edit manually.
import { DocsMetadata } from "@/types/docs.types";

const data: DocsMetadata[] = [
  {
    "id": "getting-started",
    "title": "Premiers pas avec Scintillar",
    "author": "Équipe Scintillar",
    "date": "2024-08-02",
    "description": "Apprenez à commencer avec la plateforme Scintillar et explorez ses fonctionnalités.",
    "category": "basics"
  },
  {
    "id": "settings-guide",
    "title": "Guide des paramètres de la plateforme",
    "author": "Équipe Scintillar",
    "date": "2024-08-02",
    "description": "Guide complet pour configurer et personnaliser votre expérience Scintillar.",
    "category": "configuration"
  },
  {
    "id": "digital-layers",
    "title": "Comprendre les couches numériques",
    "author": "Équipe Scintillar",
    "date": "2024-08-02",
    "description": "Guide complet pour travailler avec les couches numériques dans Scintillar.",
    "category": "features"
  },
  {
    "id": "maps-guide",
    "title": "Travailler avec les cartes",
    "author": "Équipe Scintillar",
    "date": "2024-08-02",
    "description": "Guide complet pour utiliser les outils de cartographie et de visualisation de Scintillar.",
    "category": "features"
  }
];

export default data;