// This file is generated by docs-index.script.ts. Do not edit manually.
import { DocsMetadata } from "@/types/docs.types";

const data: DocsMetadata[] = [
  {
    "id": "getting-started",
    "title": "Getting Started with Scintillar",
    "author": "Scintillar Team",
    "date": "2024-08-02",
    "description": "Learn how to get started with the Scintillar platform and explore its features.",
    "category": "basics"
  },
  {
    "id": "settings-guide",
    "title": "Platform Settings Guide",
    "author": "Scintillar Team",
    "date": "2024-08-02",
    "description": "Comprehensive guide to configuring and customizing your Scintillar experience.",
    "category": "configuration"
  },
  {
    "id": "digital-layers",
    "title": "Understanding Digital Layers",
    "author": "Scintillar Team",
    "date": "2024-08-02",
    "description": "Comprehensive guide to working with digital layers in Scintillar.",
    "category": "features"
  },
  {
    "id": "maps-guide",
    "title": "Working with Maps",
    "author": "Scintillar Team",
    "date": "2024-08-02",
    "description": "Complete guide to using Scintillar's mapping and visualization tools.",
    "category": "features"
  }
];

export default data;